name: CI

on: [push]

jobs:
  cancel_previous_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        https: ['', ssl, osx-secure-transport]
        exclude:
          - os: ubuntu-latest
            https: osx-secure-transport
          - os: windows-latest
            https: osx-secure-transport
    steps:
    - uses: actions/checkout@v1
    - name: Setup OCaml
      uses: avsm/setup-ocaml@v1.1.3
    - name: Install depext module
      run: opam install -y depext
    - name: Pin locally
      run: opam pin -y add --no-action .
    - name: Install locally
      run: opam depext -y -i ${{ matrix.https }} cry
    - name: Build locally
      run: eval $(opam env) && dune build
    - name: Run tests locally
      run: eval $(opam env) && dune runtest
